inherit_mode:
  merge:
    - Exclude

require:
  - standard
  - rubocop-performance
  - rubocop-rspec

inherit_gem:
  standard: config/base.yml
  standard-performance: config/base.yml
  standard-custom: config/base.yml

inherit_from:
  - .rubocop/custom.yml
